### ISSUE TITLE
cannot see any dag related 

### ISSUE THREAD

**Issue by xycloud** [miketmoore/horizontal-graph-theory#1]
when I clone the master clode and run 
```
npm install && bower install && npm run dev
```
it seems play a role of file server, nothing about dag. did I do anything  wrong?

**Comment by miketmoore** [comment]
Just navigate to http://localhost:3000/public/ in the browser to see the DAG. Yes, `npm run dev` starts a server.

**Comment by xycloud** [comment]
ya，I know npm run dev starts a server, just do not see any routes info or link about dag

**Comment by miketmoore** [comment]
@xycloud the DAG demo is at http://localhost:3000/public - happy to help if you can provide more details. The source code is located in the `src` directory.
